### ISSUE TITLE
英雄榜资料提交到这，回复就可以，不用重新开

### ISSUE THREAD

**Issue by jikeytang** [hunanjs/hunanjs.github.io#1]
类似这样的格式，提交时删除注释
```javascript
{
    "id": "1",
    "username": "jikeytang",
    "name": "豪情",
    "blog": "http://jikey.cnblogs.com",
    "github": "http://github.com/jikeytang",
    "website": "http://www.jscss.me", // 个人网址
    "word": "一直在打杂从未被超越", // 一句话介绍
    "avatar": "https://avatars0.githubusercontent.com/u/539745?v=3&s=400" // github默认头像
  }
```

**Comment by 956887898** [comment]
{
    "id": "3",
    "username": "arron",
    "name": "安安",
    "blog": "http://git.oschina.net/counters/",
    "github": "https://github.com/956887898",
    "website": "https://github.com/956887898", // 个人网址
    "word": "正在前端这条道路上努力前进中", // 一句话介绍
    "avatar": "https://avatars0.githubusercontent.com/u/25519798?v=3&s=40" // github默认头像
  }

**Comment by 956887898** [comment]
{
    "id": "3",
    "username": "arron",
    "name": "安安",
    "blog": "http://git.oschina.net/counters/",
    "github": "https://github.com/956887898",
    "website": "https://github.com/956887898", // 个人网址
    "word": "正在前端这条道路上努力前进中", // 一句话介绍
    "avatar": "https://avatars0.githubusercontent.com/u/539745?v=3&s=400" // github默认头像
  }

**Comment by lxlneo** [comment]
{
"id": "2",
"username": "lxlneo",
"name": "wahaha",
"blog": "http://blog.find11now.com/",
"github": "https://github.com/lxlneo",
"website": "http://blog.find11now.com/", 
"word": "前端--->呵呵哒",
"avatar": "https://avatars3.githubusercontent.com/u/1750836?v=3&s=320"
}

**Comment by zoux** [comment]
{
    "id": "4",
    "username": "zx940125",
    "name": "Zou Xin",
    "blog": "https://github.com/zx940125",
    "github": "https://github.com/zx940125",
    "website": "https://github.com/zx940125, // 个人网址
    "word": "一只前端汪", // 一句话介绍
    "avatar": "https://avatars2.githubusercontent.com/u/24969960?v=3&s=460" // github默认头像
}
